# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03e4069688c0d13ad98e776b7c3f1046c7722d86ab459ea261793434331301dbc8de3e69406d9a58adef175d67a744bee3b6167c507b693b7024a533289b4d87

test:
  secret_key_base: e3d8424a25d92a4bab9fd8cd174ce6d45a72509d6729a71b83ae6643a31572fac40a6879cb0091c8f0fe9327cfd52f4b4aa6d695a22f0ecc8a1ce9145587f1eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
